//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARS {
    
    
    public partial class NeueFahrt {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// NEUEFAHRT_FAHRTERSTELLEN_PANEL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel NEUEFAHRT_FAHRTERSTELLEN_PANEL;
        
        /// <summary>
        /// FAHRTERSTELLEN_UHRZEIT_ABFAHRT_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FAHRTERSTELLEN_UHRZEIT_ABFAHRT_TEXT;
        
        /// <summary>
        /// FAHRTERSTELLEN_UHRZEIT_ABFAHRT_CALENDER control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Calendar FAHRTERSTELLEN_UHRZEIT_ABFAHRT_CALENDER;
        
        /// <summary>
        /// FAHRTERSTELLEN_UHRZEIT_ABFAHRTSZEIT_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FAHRTERSTELLEN_UHRZEIT_ABFAHRTSZEIT_TEXT;
        
        /// <summary>
        /// FAHRTERSTELLEN_UHRZEIT_ABFAHRTSZEIT_STUNDE_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FAHRTERSTELLEN_UHRZEIT_ABFAHRTSZEIT_STUNDE_INPUT;
        
        /// <summary>
        /// FAHRTERSTELLEN_UHRZEIT_ABFAHRTSZEIT_TEXT2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FAHRTERSTELLEN_UHRZEIT_ABFAHRTSZEIT_TEXT2;
        
        /// <summary>
        /// FAHRTERSTELLEN_UHRZEIT_ABFAHRTSZEIT_MINUTE_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FAHRTERSTELLEN_UHRZEIT_ABFAHRTSZEIT_MINUTE_INPUT;
        
        /// <summary>
        /// FAHRTERSTELLEN_ABFAHRTSORT_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FAHRTERSTELLEN_ABFAHRTSORT_TEXT;
        
        /// <summary>
        /// FAHRTERSTELLEN_ABFAHRTSORT_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FAHRTERSTELLEN_ABFAHRTSORT_INPUT;
        
        /// <summary>
        /// FAHRTERSTELLEN_ZIELORT_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FAHRTERSTELLEN_ZIELORT_TEXT;
        
        /// <summary>
        /// FAHRTERSTELLEN_ZIELORT_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FAHRTERSTELLEN_ZIELORT_INPUT;
        
        /// <summary>
        /// FAHRTERSTELLEN_FREIESITZPLÄTZE_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FAHRTERSTELLEN_FREIESITZPLÄTZE_TEXT;
        
        /// <summary>
        /// FAHRTERSTELLEN_FREIESITZPLÄTZE_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FAHRTERSTELLEN_FREIESITZPLÄTZE_INPUT;
        
        /// <summary>
        /// FAHRTERSTELLEN_FAHERTERSTELLEN_BUTTON control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button FAHRTERSTELLEN_FAHERTERSTELLEN_BUTTON;
        
        /// <summary>
        /// ERROR_PANEL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ERROR_PANEL;
        
        /// <summary>
        /// ERROR_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ERROR_TEXT;
    }
}
