//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARS {
    
    
    public partial class Register {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// REGISTER_PANEL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel REGISTER_PANEL;
        
        /// <summary>
        /// REGISTER_NAME_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label REGISTER_NAME_TEXT;
        
        /// <summary>
        /// REGISTER_NAME_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox REGISTER_NAME_INPUT;
        
        /// <summary>
        /// REGISTER_EMAIL_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label REGISTER_EMAIL_TEXT;
        
        /// <summary>
        /// REGISTER_EMAIL_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox REGISTER_EMAIL_INPUT;
        
        /// <summary>
        /// REGISTER_PASSWORT_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label REGISTER_PASSWORT_TEXT;
        
        /// <summary>
        /// REGISTER_PASSWORT_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox REGISTER_PASSWORT_INPUT;
        
        /// <summary>
        /// REGISTER_PASSWORDBESTÄTIGEN_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label REGISTER_PASSWORDBESTÄTIGEN_TEXT;
        
        /// <summary>
        /// REGISTER_PASSWORDBESTÄTIGEN_INPUT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox REGISTER_PASSWORDBESTÄTIGEN_INPUT;
        
        /// <summary>
        /// REGISTER_AGB_GELESEN_CHECKBOX control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox REGISTER_AGB_GELESEN_CHECKBOX;
        
        /// <summary>
        /// REGISTER_REGISTRIEREN_BUTTON control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button REGISTER_REGISTRIEREN_BUTTON;
        
        /// <summary>
        /// REGISTER_LOGIN_BUTTON control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button REGISTER_LOGIN_BUTTON;
        
        /// <summary>
        /// ERROR_PANEL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ERROR_PANEL;
        
        /// <summary>
        /// ERROR_TEXT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ERROR_TEXT;
    }
}
